skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
q3_26_vault = "CisEvkF3DJ1f9z5DxtjuEPRRg5FVj67qTCoewwB7NrjG"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
